config:
  clusters:
    - name: "<<name your cluster>>"
      server: "https://cluster.local"

service:
  type: LoadBalancer
  port: 80

# Force Headlamp onto an 8GB node
nodeSelector:
  capacity: max

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi
